Delete処理に例外処理を追記しました。
aokiayukodesu/tasuk10-crud pull request #4
Opened 2023-08-16 06:20 UTC by aokiayukodesu

Delete処理に例外処理を追記しました。
実行すると、[Parameter 'user' not found. Available parameters are [id, param1]]とエラーが出ます。
userにパラメータの指定をして〜ということのようなので、とりあえず@Paramでuserを追記して見ましたが赤文字になり、うまくいきません。
なぜこのようなエラーが出るのでしょうか・・。
ご教授いただけますと幸いです。

2023-08-18 02:54 UTC, Shibata0806 commented on src/main/java/com/mybatis/task10/demo/UserServiceImpl.java
> +        }
[nits]
この書き方でも全然OKなのですが、Optionalクラスには`orElseThrow()`というメソッドがあり、結構便利で使ってみると良いと思います！

2023-08-18 02:57 UTC, Shibata0806 commented
`Delete処理に例外処理を追記しました。` というタイトルのPRになっていますが、内容的にはUpdateとDeleteを実装したものになっていますね。このような場合、`Update/Delete実装`みたいなタイトルで良いかなと思います！タイトルは編集できるので編集しちゃいましょう！

あと、PRの説明のところにも、やったことの説明と、curlやPostmanで動作確認したエビデンスをスクリーンショットなどで貼っておいていただけると、レビュアーが動作確認をする手間が省けるので、ぜひ貼っていただきますようお願いします！

2023-08-18 14:13 UTC, aokiayukodesu commented on src/main/java/com/mybatis/task10/demo/UserServiceImpl.java
> +        }
レビューありがとうございます！
タイトル修正させていただきました！また、PRの説明と動作確認の件承知しました。お手数おかけしてすみませんでした。今後気をつけます。

2023-08-18 14:46 UTC, Shibata0806 requested changes
すみません！前回は気づかなかったのですが、もう一点だけコメント入れましたので、ご確認くださいませ！

2023-08-18 14:46 UTC, Shibata0806 commented on src/main/java/com/mybatis/task10/demo/UserServiceImpl.java
> +    }
@aokiayukodesu updateにも、deleteと同じくidが存在するかどうかの処理を入れたほうが良いのかなと思ったのですが、いかがでしょうか？？

2023-08-18 14:55 UTC, aokiayukodesu commented on src/main/java/com/mybatis/task10/demo/UserServiceImpl.java
> +    }
あ、確かにそうですね！追記します！
あと、質問なのですが、isPresentの時は、Optional user = userMapper.findById(id);とする必要があるのに、
OrElseThrowメソッドだとそれが不要になるのは何故でしょうか？OrElseThrowもoptionalのメソッドなんですよね？

2023-08-18 15:14 UTC, Shibata0806 commented on src/main/java/com/mybatis/task10/demo/UserServiceImpl.java
> +    }
@aokiayukodesu 
ありがとうございます！
めっちゃいい質問ですね！
この書き方はメソッドチェーンと言います！1行にまとめて記載するのでわかりにくいのですが、isPresentを使うときに似せて書くとこんな感じになるんですよね！
```
        Optional<User> user = userMapper.findById(id);
        user.orElseThrow(() -> new ResourceNotFoundException("指定されたidは存在しません"));
```
ですが、上記のように、一度userという変数に代入することを省くために、1行で
```
userMapper.findById(id).orElseThrow(() -> new ResourceNotFoundException("指定されたidは存在しません"));
```
と記載するのが、Javaのプログラマーの中では一般的になっています。
慣れない書き方かもしれないですね！
ぜひ一度、`メソッドチェーン`というワードでググってみてください！

2023-08-19 11:06 UTC, Shibata0806 approved these changes

2023-08-26 00:47 UTC, merged